# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e7f702049311becb2bb6b0685358c3e6aec48c71b731cbce882f12139b16878de2f8bdf2c37593c4024c2b40904d8513a6e83a6b834b2d7c70ef473dd88d36c

test:
  secret_key_base: cf775edfe3c22b6c93d411ec89d0e78fd75f8d79a070e3b8073d24186fdc0d86659500b1136b1f1334b61c932d500d6608ab2d049bad71fc13155d44d57ffbac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
